"use client";
import Script from "next/script";
// import { Providers } from "./providers";
// import {NextUIProvider} from "@nextui-org/react";
import { Inter } from "next/font/google";
import { store } from "./redux/store";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { persistStore } from "redux-persist";
import Breadcrumb from "./components/breadcrumb/Breadcrumb";
import "./assets/css/sb-admin-2.min.css";
import "./assets/css/fontawesome.css";
import "./assets/vendor/datatables/dataTables.bootstrap4.min.css";

// import "./assets/css/animate.css";
// import "./assets/css/main.css";

import Sidebar from "./components/navbar/Sidebar";
import Topbar from "./components/navbar/Topbar";

const inter = Inter({ subsets: ["latin"] });
let persistor = persistStore(store);

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <head>
        <link rel="shortcut icon" href="#"></link>
      </head>

      <body id="page-top" suppressHydrationWarning={true} >
        {/* <NextUIProvider> */}
        <Provider store={store}>
          <PersistGate persistor={persistor}>
            <div id="wrapper">
              <Sidebar />

              <div id="content-wrapper" className="d-flex flex-column" >
                <Topbar />
                <Breadcrumb />
                {children}
              </div>
            </div>
          </PersistGate>
        </Provider>
        {/* </NextUIProvider> */}
        <Script src="vendor/jquery/jquery.min.js"></Script>
        <Script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></Script>

        <Script src="vendor/jquery-easing/jquery.easing.min.js"></Script>

        <Script src="js/sb-admin-2.min.js"></Script>
        {/* <Script src="js/wow.js" /> */}

        {/* <Script src="vendor/chart.js/Chart.min.js"></Script>

  <Script src="js/demo/chart-area-demo.js"></Script>
  <Script src="js/demo/chart-pie-demo.js"></Script> */}

        {/* <!-- Page level plugins --> */}
        <Script src="vendor/datatables/jquery.dataTables.min.js"></Script>
        <Script src="vendor/datatables/dataTables.bootstrap4.min.js"></Script>

        {/* <!-- Page level custom scripts --> */}
        <Script src="js/demo/datatables-demo.js"></Script>
      </body>
    </html>
  );
}
